//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDOK2                           3
#define IDI_ICON1                       101
#define IDI_ICON_MAIN                   101
#define IDI_ICON_Heroland               101
#define IDD_DIALOG_Main                 102
#define IDR_MENU_Main                   103
#define IDD_DIALOG_GetString            104
#define IDD_DIALOG_GetInt               105
#define IDD_DIALOG_ObjectList           106
#define IDD_DIALOG_GetName              107
#define IDD_DIALOG_ChangePoint          108
#define IDD_DIALOG_Old_CP               108
#define IDD_DIALOG_Help                 111
#define IDR_ACCELERATOR1                112
#define IDR_MENU_Window                 113
#define IDD_DIALOG_Hook                 114
#define IDD_DIALOG_Object               116
#define IDD_DIALOG_PopMenu              117
#define IDD_DIALOG_Tools                119
#define IDD_DIALOG_EnemySet             121
#define IDC_EDIT_BackGroundFileName     1000
#define IDC_EDIT_Name                   1001
#define IDC_EDIT_Width                  1002
#define IDC_EDIT_Height                 1003
#define IDC_CHECK_ShowCell              1004
#define IDC_BUTTON_ChangeBackGround     1005
#define IDC_EDIT_BackBmp                1005
#define IDC_CHECK_ShowObject            1006
#define IDC_EDIT_Message                1006
#define IDC_EDIT_String                 1007
#define IDC_CHECK_ShowBackGround        1007
#define IDC_CHECK_ShowBlock             1008
#define IDC_EDIT_Int                    1009
#define IDC_CHECK_ShowCurrent           1009
#define IDC_BUTTON_Advance              1010
#define IDC_LIST_Objects                1011
#define IDC_CHECK_ShowEdit              1011
#define IDC_EDIT_FileName               1012
#define IDC_BUTTON_ChangePoint          1012
#define IDC_BUTTON_Object               1013
#define IDC_BUTTON_Cell                 1014
#define IDC_CHECK_ShowOnlyObject        1014
#define IDC_BUTTON_Add                  1015
#define IDC_BUTTON_Hook                 1015
#define IDC_BUTTON_Enemy                1015
#define IDC_BUTTON_Delete               1016
#define IDC_LIST_Name                   1016
#define IDC_BUTTON_Main                 1016
#define IDC_BUTTON_Modify               1017
#define IDC_BUTTON_DelHook              1017
#define IDC_EDIT_Id                     1018
#define IDC_EDIT_Dir                    1019
#define IDC_LIST_ChangePoint            1020
#define IDC_EDIT_x                      1021
#define IDC_LIST_AllEnemy               1021
#define IDC_EDIT_y                      1022
#define IDC_EDIT_ox                     1023
#define IDC_EDIT_oy                     1024
#define IDC_BUTTON_Browe                1025
#define IDC_COMBO_Dir                   1026
#define IDC_COMBO_In                    1027
#define IDC_COMBO_Out                   1028
#define IDC_EDIT_Fps                    1028
#define IDC_CHECK_Across                1029
#define IDC_EDIT_Reason                 1030
#define IDC_COMBO_Level                 1031
#define IDC_RADIO_Up                    1033
#define IDC_RADIO_Normal                1034
#define IDC_RADIO_Up2                   1035
#define IDC_EDIT_Ground                 1036
#define IDC_EDIT_Object                 1037
#define IDC_EDIT_GroundPage             1038
#define IDC_EDIT_ObjectPage             1039
#define IDC_EDIT_Hook                   1040
#define IDC_CHECK_Block                 1041
#define IDC_BUTTON_Ground               1042
#define IDC_EDIT_Object2                1042
#define IDC_EDIT_ObjectPage2            1043
#define IDC_RADIO_Normal2               1044
#define IDC_BUTTON1                     1044
#define IDC_LIST_Enemy                  1046
#define IDC_SLIDER_Enemy                1048
#define IDC_EDIT_Freq                   1049
#define IDC_COMBO_CPType                1050
#define IDC_COMBO_HOOKTYPE              1053
#define ID_MENUITEM_Open                40001
#define ID_MENUITEM_Save                40002
#define ID_MENUITEM_Exit                40004
#define ID_MENUITEM_New                 40005
#define ID_MENUITEM_About               40006
#define ID_MENUITEM_640                 40007
#define ID_MENUITEM_800                 40008
#define ID_MENUITEM_1024                40009
#define ID_MENUITEM_SaveAs              40011
#define ID_MENUITEM_Help                40012
#define IDM_ChangeDisplayMode           40013
#define IDM_Exit                        40014
#define ID_MENUITEM_ReOpen              40016
#define ID_MENUITEM_Undo                40017
#define ID_MENUITEM_SelGround           40018
#define ID_MENUITEM_SelObject           40019
#define ID_MENUITEM_Cell                40020
#define ID_MENUITEM_Map                 40021
#define ID_MENUITEM_SetHook             40022
#define ID_MENUITEM_DelHook             40023
#define ID_MENUITEM_FullMap             40025
#define ID_MENUITEM_ShowCell            40026
#define ID_MENUITEM_ShowObject          40027
#define ID_MENUITEM_ShowBlock           40028
#define ID_MENUITEM_ShowCurrent         40029
#define ID_MENUITEM_ShowEdit            40030
#define ID_MENUITEM_ShowObjectOnly      40031
#define ID_MENUITEM_SelObject2          40032
#define ID_MENUITEM_Ground              40033
#define ID_MENUITEM_Object              40034
#define ID_MENUITEM_Object2             40035
#define ID_MENUITEM_Load                40037
#define ID_MENUITEM_RestoreLevel        40042
#define ID_MENUITEM_RestoreBlock        40043
#define ID_MENUITEM_Cancel              40044
#define ID_MENUITEM_Enemy               40045
#define ID_MENUITEM_SelAni              40046
#define ID_MENUITEM_SaveFullMap         40047
#define ID_MENUITEM_RestoreMouseType    40048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40049
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
